config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'gallery/index'
  get 'gallery/search'
  post 'gallery/search'
  get 'gallery/checkout'
  resources :stores
  get 'admin/login'
  post 'admin/login'
  get 'admin/logout'
  devise_for :users
  get 'welcome/index'
  post 'gallery/checkout'
  get 'gallery/purchase_complete'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "welcome#index"
end

app/models/store.rb
class Store < ApplicationRecord
    has_one_attached :product_image
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]
  before_action :admin_loggedin? 

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy!

    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end
    def admin_loggedin?   
      if session[:admin].nil?
        flash[:notice] = "You need to login as as Admin to continue"
        redirect_to admin_login_url
      end
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :category, :description, :price, :ingredients, :made_without, :packaging, :certifications,:product_image)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <%= form.label :product_image , style: "display: block" %>
  <%= form.file_field :product_image %>

  <div>
    <%= form.label :ingredients, style: "display: block" %>
    <%= form.text_area :ingredients %>
  </div>

  <div>
    <%= form.label :made_without, style: "display: block" %>
    <%= form.text_area :made_without %>
  </div>

  <div>
    <%= form.label :packaging, style: "display: block" %>
    <%= form.text_area :packaging %>
  </div>

  <div>
    <%= form.label :certifications, style: "display: block" %>
    <%= form.text_area :certifications %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">
  <p>
    <strong>Name:</strong>
    <%= store.name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= store.category %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= store.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= store.price %>
  </p>

  <% if store.product_image.attached? %>
<%= image_tag store.product_image ,height: "100",width: "75"%>
<% end %>

  <p>
    <strong>Ingredients:</strong>
    <%= store.ingredients %>
  </p>

  <p>
    <strong>Made without:</strong>
    <%= store.made_without %>
  </p>

  <p>
    <strong>Packaging:</strong>
    <%= store.packaging %>
  </p>

  <p>
    <strong>Certifications:</strong>
    <%= store.certifications %>
  </p>

</div>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Show this store", @store %> |
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

<h1>Stores</h1>

<div id="stores">
  <% @stores.each do |store| %>
    <%= render store %>
    <p>
      <%= link_to "Show this product", store ,class:"btn btn-outline-primary"%>
    </p>
  <% end %>
</div>

</div>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/show.html.erb
<div class="container p-4">
  <p style="color: green"><%= notice %></p>

<%= render @store %>

<div class="d-flex">
  <%= link_to "Edit this store", edit_store_path(@store) ,class:'btn btn-outline-primary me-3'%> 
  <%= link_to "Back to stores", stores_path,class:'btn btn-outline-primary me-3' %>

  <%= button_to "Destroy this store", @store, method: :delete,class:'btn btn-outline-primary' %>
</div>

</div>