config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'gallery/index'
  get 'gallery/search'
  post 'gallery/search'
  get 'gallery/checkout'
  resources :stores
  get 'admin/login'
  post 'admin/login'
  get 'admin/logout'
  devise_for :users
  get 'welcome/index'
  post 'gallery/checkout'
  get 'gallery/purchase_complete'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "welcome#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerceSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
              
<link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.2/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.3/components/footers/footer-2/assets/css/footer-2.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# Navbar %>
    <nav class="navbar navbar-expand-lg navbar-dark gradient-custom" id="navbar">
  <div class="container-fluid">
     <% if user_signed_in? %>
    <a class="navbar-brand" href="/welcome/index">Eco-Sus-Shop</a>
    <%else%>
    <%= link_to "Eco-Sus-Shop", new_user_session_path, class: "navbar-brand"  %>
    <%end%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Products", gallery_index_path, class: "nav-link active" %> 
        </li>
        <li class="nav-item">
            <%= link_to "Cart", carts_path, class: "nav-link active" %> 
        </li>
        <li class="nav-item">
            <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link active" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link active"  %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link active"  %> 
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link active"  %>
        </li>
        
        <%end%>
        <% if session[:admin] %>
        <li class="nav-item">
        <a href="/admin/logout" class="nav-link active">Admin Logout</a>
        </li>
         <% else %>
         <li class="nav-item">
        <a href="/admin/login" class="nav-link active">Admin Login</a>
        </li>
        <% end %>
    </div>
    <% if user_signed_in? %>
    <li class="nav-item d-flex">
              <%= form_with url: "/gallery/search",html: {class:"form-style"}, method: :get do |form| %>
              <%= form.label :query, "Search for:" ,class:"text-light me-1" %>
<%= form.text_field :keyword ,class:'form-control w-50'%>
<%= form.submit "Search" ,class:'button-70'%>
<% end %>
        </li>
    <div class="navbar-text text-light">Logged in as <strong><%= current_user.email %></strong></div>
    <%end%>
  </div>
</nav>
    <%# Navbar %>
    <%# Navbar %>

     <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
    <%# Footer %>
    
    <%# Footer %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>